package db

import (
	"procure-ai/models"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

func SeedVendors(database *gorm.DB) error {
	vendors := []models.Vendor{
		// Electronics (original)
		{Name: "Alpha Industrial Supply", Price: 94.50, Trust: 4.8, DeliveryDays: 2, Stock: 450, MinOrderQty: 20, Location: "Mumbai", PaymentTerms: "Net 15", ReliabilityScore: 96, Category: "electronics"},
		{Name: "Nova Parts Co", Price: 88.90, Trust: 4.2, DeliveryDays: 5, Stock: 900, MinOrderQty: 50, Location: "Pune", PaymentTerms: "Net 30", ReliabilityScore: 89, Category: "electronics"},
		{Name: "Rapid Source Logistics", Price: 102.25, Trust: 4.7, DeliveryDays: 1, Stock: 320, MinOrderQty: 10, Location: "Bengaluru", PaymentTerms: "Advance 30%", ReliabilityScore: 94, Category: "electronics"},
		{Name: "Eco Wholesale Hub", Price: 84.00, Trust: 3.9, DeliveryDays: 6, Stock: 1200, MinOrderQty: 100, Location: "Ahmedabad", PaymentTerms: "Net 45", ReliabilityScore: 82, Category: "electronics"},
		{Name: "Prime Vendor Network", Price: 97.10, Trust: 4.9, DeliveryDays: 3, Stock: 500, MinOrderQty: 25, Location: "Hyderabad", PaymentTerms: "Net 15", ReliabilityScore: 98, Category: "electronics"},
		{Name: "Sterling Components", Price: 91.75, Trust: 4.5, DeliveryDays: 4, Stock: 650, MinOrderQty: 30, Location: "Chennai", PaymentTerms: "Net 30", ReliabilityScore: 91, Category: "electronics"},
		{Name: "Summit Procurement", Price: 86.30, Trust: 4.1, DeliveryDays: 7, Stock: 1500, MinOrderQty: 150, Location: "Surat", PaymentTerms: "Net 45", ReliabilityScore: 85, Category: "electronics"},
		{Name: "Vertex Trade Links", Price: 99.80, Trust: 4.6, DeliveryDays: 2, Stock: 280, MinOrderQty: 20, Location: "Delhi", PaymentTerms: "Net 21", ReliabilityScore: 93, Category: "electronics"},
		{Name: "BluePeak Supplies", Price: 89.40, Trust: 4.3, DeliveryDays: 5, Stock: 720, MinOrderQty: 40, Location: "Noida", PaymentTerms: "Net 30", ReliabilityScore: 88, Category: "electronics"},
		{Name: "Atlas Commerce", Price: 95.20, Trust: 4.4, DeliveryDays: 3, Stock: 410, MinOrderQty: 15, Location: "Kolkata", PaymentTerms: "Net 20", ReliabilityScore: 90, Category: "electronics"},
		// Medical (original)
		{Name: "Zenith MedTech Supply", Price: 148.00, Trust: 4.9, DeliveryDays: 2, Stock: 180, MinOrderQty: 5, Location: "Mumbai", PaymentTerms: "Net 10", ReliabilityScore: 97, Category: "medical"},
		{Name: "CareAxis Distributors", Price: 132.60, Trust: 4.5, DeliveryDays: 4, Stock: 260, MinOrderQty: 10, Location: "Delhi", PaymentTerms: "Net 20", ReliabilityScore: 92, Category: "medical"},
		{Name: "MediSure Wholesale", Price: 126.40, Trust: 4.0, DeliveryDays: 6, Stock: 540, MinOrderQty: 30, Location: "Jaipur", PaymentTerms: "Net 30", ReliabilityScore: 86, Category: "medical"},
		{Name: "PulseLine Vendors", Price: 141.75, Trust: 4.7, DeliveryDays: 3, Stock: 220, MinOrderQty: 8, Location: "Hyderabad", PaymentTerms: "Advance 20%", ReliabilityScore: 95, Category: "medical"},
		{Name: "Helix Health Source", Price: 119.90, Trust: 3.8, DeliveryDays: 8, Stock: 800, MinOrderQty: 50, Location: "Lucknow", PaymentTerms: "Net 45", ReliabilityScore: 81, Category: "medical"},
		// Raw Materials (original)
		{Name: "ForgeRaw Materials", Price: 72.20, Trust: 4.3, DeliveryDays: 5, Stock: 2000, MinOrderQty: 200, Location: "Nagpur", PaymentTerms: "Net 30", ReliabilityScore: 87, Category: "raw_materials"},
		{Name: "IronBridge Traders", Price: 69.85, Trust: 4.0, DeliveryDays: 7, Stock: 2600, MinOrderQty: 300, Location: "Jamshedpur", PaymentTerms: "Net 45", ReliabilityScore: 84, Category: "raw_materials"},
		{Name: "Titan SourceWorks", Price: 76.40, Trust: 4.8, DeliveryDays: 3, Stock: 1100, MinOrderQty: 120, Location: "Vadodara", PaymentTerms: "Net 15", ReliabilityScore: 96, Category: "raw_materials"},
		{Name: "CoreBulk Industries", Price: 71.60, Trust: 3.9, DeliveryDays: 9, Stock: 3200, MinOrderQty: 500, Location: "Raipur", PaymentTerms: "Net 60", ReliabilityScore: 80, Category: "raw_materials"},
		{Name: "Harbor Line Supply", Price: 74.95, Trust: 4.6, DeliveryDays: 4, Stock: 1450, MinOrderQty: 150, Location: "Visakhapatnam", PaymentTerms: "Net 21", ReliabilityScore: 93, Category: "raw_materials"},

		// Electronics (new)
		{Name: "CircuitPath Traders", Price: 91.00, Trust: 4.4, DeliveryDays: 3, Stock: 560, MinOrderQty: 25, Location: "Bengaluru", PaymentTerms: "Net 30", ReliabilityScore: 89, Category: "electronics"},
		{Name: "PixelCore Supplies", Price: 104.50, Trust: 4.7, DeliveryDays: 2, Stock: 300, MinOrderQty: 10, Location: "Hyderabad", PaymentTerms: "Net 15", ReliabilityScore: 95, Category: "electronics"},
		{Name: "NexGen Components", Price: 87.60, Trust: 4.1, DeliveryDays: 6, Stock: 1100, MinOrderQty: 60, Location: "Pune", PaymentTerms: "Net 45", ReliabilityScore: 84, Category: "electronics"},
		{Name: "Omega Tech Parts", Price: 93.30, Trust: 4.5, DeliveryDays: 4, Stock: 480, MinOrderQty: 20, Location: "Chennai", PaymentTerms: "Net 20", ReliabilityScore: 91, Category: "electronics"},
		{Name: "FluxLine Distributors", Price: 98.70, Trust: 4.6, DeliveryDays: 3, Stock: 390, MinOrderQty: 15, Location: "Mumbai", PaymentTerms: "Net 21", ReliabilityScore: 93, Category: "electronics"},
		{Name: "CatalystTech Wholesale", Price: 85.20, Trust: 3.8, DeliveryDays: 7, Stock: 1350, MinOrderQty: 100, Location: "Ahmedabad", PaymentTerms: "Net 60", ReliabilityScore: 80, Category: "electronics"},
		{Name: "PeakSignal Traders", Price: 100.40, Trust: 4.8, DeliveryDays: 2, Stock: 270, MinOrderQty: 10, Location: "Delhi", PaymentTerms: "Net 15", ReliabilityScore: 96, Category: "electronics"},
		{Name: "VoltEdge Commerce", Price: 92.80, Trust: 4.3, DeliveryDays: 5, Stock: 710, MinOrderQty: 35, Location: "Noida", PaymentTerms: "Net 30", ReliabilityScore: 88, Category: "electronics"},
		{Name: "PrismBoard Supply", Price: 96.50, Trust: 4.4, DeliveryDays: 4, Stock: 530, MinOrderQty: 20, Location: "Kolkata", PaymentTerms: "Net 20", ReliabilityScore: 90, Category: "electronics"},
		{Name: "IntelliParts Hub", Price: 89.90, Trust: 4.2, DeliveryDays: 5, Stock: 860, MinOrderQty: 50, Location: "Surat", PaymentTerms: "Net 30", ReliabilityScore: 87, Category: "electronics"},
		{Name: "DigiRoute Vendors", Price: 105.00, Trust: 4.9, DeliveryDays: 1, Stock: 240, MinOrderQty: 10, Location: "Bengaluru", PaymentTerms: "Advance 25%", ReliabilityScore: 97, Category: "electronics"},
		{Name: "ByteSource India", Price: 82.40, Trust: 3.7, DeliveryDays: 8, Stock: 1600, MinOrderQty: 120, Location: "Indore", PaymentTerms: "Net 45", ReliabilityScore: 79, Category: "electronics"},
		{Name: "AmpTech Traders", Price: 94.00, Trust: 4.5, DeliveryDays: 3, Stock: 470, MinOrderQty: 25, Location: "Hyderabad", PaymentTerms: "Net 15", ReliabilityScore: 92, Category: "electronics"},
		{Name: "NanoGrid Supplies", Price: 101.60, Trust: 4.6, DeliveryDays: 2, Stock: 310, MinOrderQty: 15, Location: "Mumbai", PaymentTerms: "Net 21", ReliabilityScore: 94, Category: "electronics"},
		{Name: "ElectraHub Network", Price: 90.25, Trust: 4.3, DeliveryDays: 4, Stock: 620, MinOrderQty: 30, Location: "Pune", PaymentTerms: "Net 30", ReliabilityScore: 89, Category: "electronics"},
		{Name: "QuantumParts Co", Price: 97.75, Trust: 4.7, DeliveryDays: 3, Stock: 400, MinOrderQty: 20, Location: "Delhi", PaymentTerms: "Net 15", ReliabilityScore: 95, Category: "electronics"},
		{Name: "Radiant Tech Wholesale", Price: 86.90, Trust: 4.0, DeliveryDays: 6, Stock: 980, MinOrderQty: 75, Location: "Chennai", PaymentTerms: "Net 30", ReliabilityScore: 85, Category: "electronics"},
		{Name: "SwiftCircuit Traders", Price: 103.10, Trust: 4.8, DeliveryDays: 2, Stock: 260, MinOrderQty: 10, Location: "Bengaluru", PaymentTerms: "Net 15", ReliabilityScore: 96, Category: "electronics"},
		{Name: "GridLink Distributors", Price: 88.50, Trust: 4.2, DeliveryDays: 5, Stock: 840, MinOrderQty: 45, Location: "Ahmedabad", PaymentTerms: "Net 30", ReliabilityScore: 87, Category: "electronics"},
		{Name: "TechNova Procure", Price: 95.80, Trust: 4.4, DeliveryDays: 4, Stock: 500, MinOrderQty: 20, Location: "Kolkata", PaymentTerms: "Net 20", ReliabilityScore: 91, Category: "electronics"},
		{Name: "Pulse Electronics Hub", Price: 92.00, Trust: 4.3, DeliveryDays: 5, Stock: 690, MinOrderQty: 35, Location: "Noida", PaymentTerms: "Net 30", ReliabilityScore: 88, Category: "electronics"},
		{Name: "MicroLink Parts", Price: 99.30, Trust: 4.6, DeliveryDays: 3, Stock: 370, MinOrderQty: 15, Location: "Hyderabad", PaymentTerms: "Net 21", ReliabilityScore: 93, Category: "electronics"},
		{Name: "SignalPath Wholesale", Price: 84.70, Trust: 3.9, DeliveryDays: 7, Stock: 1250, MinOrderQty: 100, Location: "Surat", PaymentTerms: "Net 45", ReliabilityScore: 83, Category: "electronics"},
		{Name: "Horizon Electronics", Price: 107.00, Trust: 4.9, DeliveryDays: 1, Stock: 200, MinOrderQty: 5, Location: "Mumbai", PaymentTerms: "Advance 30%", ReliabilityScore: 98, Category: "electronics"},
		{Name: "ClearVolt Suppliers", Price: 90.60, Trust: 4.4, DeliveryDays: 4, Stock: 550, MinOrderQty: 25, Location: "Delhi", PaymentTerms: "Net 20", ReliabilityScore: 90, Category: "electronics"},
		{Name: "OmniBoard Traders", Price: 83.50, Trust: 4.0, DeliveryDays: 6, Stock: 1050, MinOrderQty: 80, Location: "Jaipur", PaymentTerms: "Net 45", ReliabilityScore: 84, Category: "electronics"},
		{Name: "Northgate Tech Parts", Price: 96.20, Trust: 4.5, DeliveryDays: 3, Stock: 430, MinOrderQty: 20, Location: "Chandigarh", PaymentTerms: "Net 15", ReliabilityScore: 92, Category: "electronics"},
		{Name: "TrueVolt Distributors", Price: 93.90, Trust: 4.3, DeliveryDays: 5, Stock: 730, MinOrderQty: 40, Location: "Kochi", PaymentTerms: "Net 30", ReliabilityScore: 89, Category: "electronics"},
		{Name: "SkyBridge Supplies", Price: 101.00, Trust: 4.7, DeliveryDays: 2, Stock: 290, MinOrderQty: 10, Location: "Bengaluru", PaymentTerms: "Net 15", ReliabilityScore: 95, Category: "electronics"},
		{Name: "EagleTech Commerce", Price: 87.30, Trust: 4.1, DeliveryDays: 6, Stock: 920, MinOrderQty: 60, Location: "Bhopal", PaymentTerms: "Net 45", ReliabilityScore: 85, Category: "electronics"},
		{Name: "WireFrame Vendors", Price: 94.80, Trust: 4.4, DeliveryDays: 4, Stock: 490, MinOrderQty: 20, Location: "Nagpur", PaymentTerms: "Net 20", ReliabilityScore: 91, Category: "electronics"},

		// Medical (new)
		{Name: "VitalCare Distributors", Price: 135.50, Trust: 4.6, DeliveryDays: 3, Stock: 200, MinOrderQty: 8, Location: "Bengaluru", PaymentTerms: "Net 15", ReliabilityScore: 94, Category: "medical"},
		{Name: "MediRoute Wholesale", Price: 122.80, Trust: 4.2, DeliveryDays: 5, Stock: 420, MinOrderQty: 20, Location: "Pune", PaymentTerms: "Net 30", ReliabilityScore: 88, Category: "medical"},
		{Name: "BioSync Suppliers", Price: 145.20, Trust: 4.8, DeliveryDays: 2, Stock: 160, MinOrderQty: 5, Location: "Mumbai", PaymentTerms: "Net 10", ReliabilityScore: 96, Category: "medical"},
		{Name: "NovaMed Traders", Price: 128.40, Trust: 4.3, DeliveryDays: 4, Stock: 310, MinOrderQty: 15, Location: "Delhi", PaymentTerms: "Net 20", ReliabilityScore: 90, Category: "medical"},
		{Name: "LifeBridge Supplies", Price: 138.90, Trust: 4.7, DeliveryDays: 3, Stock: 190, MinOrderQty: 6, Location: "Hyderabad", PaymentTerms: "Advance 20%", ReliabilityScore: 95, Category: "medical"},
		{Name: "ClinCore Distributors", Price: 117.60, Trust: 3.9, DeliveryDays: 7, Stock: 650, MinOrderQty: 40, Location: "Lucknow", PaymentTerms: "Net 45", ReliabilityScore: 82, Category: "medical"},
		{Name: "ApexHealth Wholesale", Price: 143.00, Trust: 4.9, DeliveryDays: 2, Stock: 175, MinOrderQty: 5, Location: "Chennai", PaymentTerms: "Net 10", ReliabilityScore: 97, Category: "medical"},
		{Name: "SafeMed Commerce", Price: 130.75, Trust: 4.5, DeliveryDays: 4, Stock: 280, MinOrderQty: 12, Location: "Kolkata", PaymentTerms: "Net 21", ReliabilityScore: 92, Category: "medical"},
		{Name: "MedixLink Vendors", Price: 124.30, Trust: 4.1, DeliveryDays: 6, Stock: 490, MinOrderQty: 25, Location: "Jaipur", PaymentTerms: "Net 30", ReliabilityScore: 87, Category: "medical"},
		{Name: "TheraCare Supply", Price: 150.60, Trust: 4.8, DeliveryDays: 2, Stock: 140, MinOrderQty: 4, Location: "Mumbai", PaymentTerms: "Net 10", ReliabilityScore: 97, Category: "medical"},
		{Name: "OmniHealth Traders", Price: 127.90, Trust: 4.4, DeliveryDays: 5, Stock: 350, MinOrderQty: 15, Location: "Ahmedabad", PaymentTerms: "Net 30", ReliabilityScore: 90, Category: "medical"},
		{Name: "ProMedix Distributors", Price: 136.00, Trust: 4.6, DeliveryDays: 3, Stock: 210, MinOrderQty: 8, Location: "Bengaluru", PaymentTerms: "Net 15", ReliabilityScore: 93, Category: "medical"},
		{Name: "HealthAxis Source", Price: 120.50, Trust: 3.8, DeliveryDays: 8, Stock: 720, MinOrderQty: 50, Location: "Patna", PaymentTerms: "Net 45", ReliabilityScore: 80, Category: "medical"},
		{Name: "CurePath Wholesale", Price: 139.25, Trust: 4.7, DeliveryDays: 3, Stock: 195, MinOrderQty: 6, Location: "Delhi", PaymentTerms: "Net 15", ReliabilityScore: 95, Category: "medical"},
		{Name: "GlobeMed Suppliers", Price: 133.80, Trust: 4.5, DeliveryDays: 4, Stock: 255, MinOrderQty: 10, Location: "Noida", PaymentTerms: "Net 20", ReliabilityScore: 91, Category: "medical"},
		{Name: "BioTrack Distributors", Price: 118.40, Trust: 4.0, DeliveryDays: 7, Stock: 580, MinOrderQty: 35, Location: "Bhopal", PaymentTerms: "Net 30", ReliabilityScore: 85, Category: "medical"},
		{Name: "ClearMed Traders", Price: 142.10, Trust: 4.8, DeliveryDays: 2, Stock: 165, MinOrderQty: 5, Location: "Hyderabad", PaymentTerms: "Net 10", ReliabilityScore: 96, Category: "medical"},
		{Name: "EliteMed Commerce", Price: 129.60, Trust: 4.3, DeliveryDays: 5, Stock: 330, MinOrderQty: 20, Location: "Chennai", PaymentTerms: "Net 30", ReliabilityScore: 89, Category: "medical"},
		{Name: "SafePlus Medical", Price: 146.00, Trust: 4.9, DeliveryDays: 1, Stock: 120, MinOrderQty: 3, Location: "Mumbai", PaymentTerms: "Advance 25%", ReliabilityScore: 98, Category: "medical"},
		{Name: "Medivault Supply", Price: 123.70, Trust: 4.2, DeliveryDays: 6, Stock: 460, MinOrderQty: 25, Location: "Kochi", PaymentTerms: "Net 30", ReliabilityScore: 87, Category: "medical"},
		{Name: "NovaPulse Distributors", Price: 137.50, Trust: 4.6, DeliveryDays: 3, Stock: 220, MinOrderQty: 8, Location: "Pune", PaymentTerms: "Net 21", ReliabilityScore: 93, Category: "medical"},
		{Name: "LifeSpring Wholesale", Price: 115.80, Trust: 3.7, DeliveryDays: 9, Stock: 800, MinOrderQty: 60, Location: "Lucknow", PaymentTerms: "Net 60", ReliabilityScore: 79, Category: "medical"},
		{Name: "MedShift Traders", Price: 131.20, Trust: 4.4, DeliveryDays: 4, Stock: 270, MinOrderQty: 10, Location: "Jaipur", PaymentTerms: "Net 20", ReliabilityScore: 90, Category: "medical"},
		{Name: "BrightMed Source", Price: 144.00, Trust: 4.7, DeliveryDays: 2, Stock: 150, MinOrderQty: 5, Location: "Delhi", PaymentTerms: "Net 15", ReliabilityScore: 95, Category: "medical"},
		{Name: "SwiftHealth Vendors", Price: 125.90, Trust: 4.1, DeliveryDays: 6, Stock: 510, MinOrderQty: 30, Location: "Ahmedabad", PaymentTerms: "Net 45", ReliabilityScore: 86, Category: "medical"},
		{Name: "MediForce Supplies", Price: 140.30, Trust: 4.8, DeliveryDays: 2, Stock: 170, MinOrderQty: 5, Location: "Bengaluru", PaymentTerms: "Net 10", ReliabilityScore: 97, Category: "medical"},
		{Name: "HealthLink Commerce", Price: 121.60, Trust: 3.9, DeliveryDays: 7, Stock: 640, MinOrderQty: 40, Location: "Kolkata", PaymentTerms: "Net 45", ReliabilityScore: 83, Category: "medical"},
		{Name: "TrueHealth Distributors", Price: 134.40, Trust: 4.5, DeliveryDays: 4, Stock: 240, MinOrderQty: 10, Location: "Hyderabad", PaymentTerms: "Net 20", ReliabilityScore: 92, Category: "medical"},
		{Name: "MedNova Wholesale", Price: 116.70, Trust: 3.8, DeliveryDays: 8, Stock: 760, MinOrderQty: 55, Location: "Nagpur", PaymentTerms: "Net 45", ReliabilityScore: 81, Category: "medical"},
		{Name: "SureSeal Medical", Price: 147.80, Trust: 4.9, DeliveryDays: 1, Stock: 130, MinOrderQty: 3, Location: "Mumbai", PaymentTerms: "Advance 30%", ReliabilityScore: 98, Category: "medical"},
		{Name: "VitalEdge Traders", Price: 128.00, Trust: 4.3, DeliveryDays: 5, Stock: 380, MinOrderQty: 15, Location: "Chennai", PaymentTerms: "Net 30", ReliabilityScore: 89, Category: "medical"},
		{Name: "CliniPath Suppliers", Price: 136.90, Trust: 4.6, DeliveryDays: 3, Stock: 200, MinOrderQty: 7, Location: "Delhi", PaymentTerms: "Net 15", ReliabilityScore: 94, Category: "medical"},
		{Name: "MediQuest Distributors", Price: 119.20, Trust: 4.0, DeliveryDays: 7, Stock: 590, MinOrderQty: 35, Location: "Surat", PaymentTerms: "Net 30", ReliabilityScore: 85, Category: "medical"},
		{Name: "PharmaRoute Wholesale", Price: 141.50, Trust: 4.7, DeliveryDays: 2, Stock: 155, MinOrderQty: 5, Location: "Hyderabad", PaymentTerms: "Net 10", ReliabilityScore: 95, Category: "medical"},

		// Raw Materials (new)
		{Name: "SteelPath Suppliers", Price: 68.40, Trust: 4.2, DeliveryDays: 6, Stock: 2800, MinOrderQty: 250, Location: "Jamshedpur", PaymentTerms: "Net 30", ReliabilityScore: 87, Category: "raw_materials"},
		{Name: "GraniteCore Traders", Price: 65.80, Trust: 3.8, DeliveryDays: 9, Stock: 3500, MinOrderQty: 500, Location: "Rajkot", PaymentTerms: "Net 60", ReliabilityScore: 79, Category: "raw_materials"},
		{Name: "AlloyBridge Wholesale", Price: 78.60, Trust: 4.7, DeliveryDays: 3, Stock: 1200, MinOrderQty: 100, Location: "Vadodara", PaymentTerms: "Net 15", ReliabilityScore: 95, Category: "raw_materials"},
		{Name: "CopperLine Distributors", Price: 73.20, Trust: 4.4, DeliveryDays: 5, Stock: 1600, MinOrderQty: 150, Location: "Bengaluru", PaymentTerms: "Net 21", ReliabilityScore: 91, Category: "raw_materials"},
		{Name: "MetalWorks Source", Price: 70.50, Trust: 4.1, DeliveryDays: 7, Stock: 2400, MinOrderQty: 300, Location: "Nagpur", PaymentTerms: "Net 45", ReliabilityScore: 85, Category: "raw_materials"},
		{Name: "OreBridge Traders", Price: 67.90, Trust: 3.9, DeliveryDays: 8, Stock: 3100, MinOrderQty: 400, Location: "Raipur", PaymentTerms: "Net 60", ReliabilityScore: 81, Category: "raw_materials"},
		{Name: "FusionRaw Suppliers", Price: 80.30, Trust: 4.8, DeliveryDays: 2, Stock: 950, MinOrderQty: 80, Location: "Hyderabad", PaymentTerms: "Advance 20%", ReliabilityScore: 96, Category: "raw_materials"},
		{Name: "CrystalOre Commerce", Price: 75.70, Trust: 4.5, DeliveryDays: 4, Stock: 1350, MinOrderQty: 120, Location: "Visakhapatnam", PaymentTerms: "Net 20", ReliabilityScore: 92, Category: "raw_materials"},
		{Name: "DuraSteel Wholesale", Price: 71.00, Trust: 4.0, DeliveryDays: 7, Stock: 2700, MinOrderQty: 350, Location: "Jamshedpur", PaymentTerms: "Net 45", ReliabilityScore: 84, Category: "raw_materials"},
		{Name: "NexAlloy Distributors", Price: 77.85, Trust: 4.6, DeliveryDays: 3, Stock: 1050, MinOrderQty: 100, Location: "Vadodara", PaymentTerms: "Net 15", ReliabilityScore: 93, Category: "raw_materials"},
		{Name: "GroundLink Raw", Price: 63.40, Trust: 3.7, DeliveryDays: 10, Stock: 4000, MinOrderQty: 600, Location: "Bhubaneswar", PaymentTerms: "Net 60", ReliabilityScore: 77, Category: "raw_materials"},
		{Name: "SilverOre Traders", Price: 79.10, Trust: 4.7, DeliveryDays: 3, Stock: 1100, MinOrderQty: 90, Location: "Nagpur", PaymentTerms: "Net 21", ReliabilityScore: 94, Category: "raw_materials"},
		{Name: "RawBridge Suppliers", Price: 72.60, Trust: 4.3, DeliveryDays: 5, Stock: 1800, MinOrderQty: 200, Location: "Raipur", PaymentTerms: "Net 30", ReliabilityScore: 88, Category: "raw_materials"},
		{Name: "MineLink Commerce", Price: 66.70, Trust: 3.8, DeliveryDays: 9, Stock: 3300, MinOrderQty: 450, Location: "Ranchi", PaymentTerms: "Net 60", ReliabilityScore: 80, Category: "raw_materials"},
		{Name: "BaseMetal Wholesale", Price: 74.20, Trust: 4.4, DeliveryDays: 5, Stock: 1550, MinOrderQty: 150, Location: "Visakhapatnam", PaymentTerms: "Net 30", ReliabilityScore: 90, Category: "raw_materials"},
		{Name: "OreTrack Distributors", Price: 69.50, Trust: 4.1, DeliveryDays: 7, Stock: 2500, MinOrderQty: 280, Location: "Jamshedpur", PaymentTerms: "Net 45", ReliabilityScore: 85, Category: "raw_materials"},
		{Name: "Purecite Source", Price: 81.00, Trust: 4.9, DeliveryDays: 2, Stock: 880, MinOrderQty: 70, Location: "Bengaluru", PaymentTerms: "Net 10", ReliabilityScore: 97, Category: "raw_materials"},
		{Name: "MassRaw Traders", Price: 68.90, Trust: 3.9, DeliveryDays: 8, Stock: 3000, MinOrderQty: 400, Location: "Raipur", PaymentTerms: "Net 60", ReliabilityScore: 82, Category: "raw_materials"},
		{Name: "ForgeLink Suppliers", Price: 75.50, Trust: 4.5, DeliveryDays: 4, Stock: 1400, MinOrderQty: 130, Location: "Vadodara", PaymentTerms: "Net 20", ReliabilityScore: 91, Category: "raw_materials"},
		{Name: "CrateAlloy Wholesale", Price: 70.80, Trust: 4.2, DeliveryDays: 6, Stock: 2200, MinOrderQty: 220, Location: "Nagpur", PaymentTerms: "Net 30", ReliabilityScore: 87, Category: "raw_materials"},
		{Name: "SummitOre Commerce", Price: 77.30, Trust: 4.6, DeliveryDays: 3, Stock: 1000, MinOrderQty: 90, Location: "Hyderabad", PaymentTerms: "Net 21", ReliabilityScore: 93, Category: "raw_materials"},
		{Name: "LithiumPath Traders", Price: 83.60, Trust: 4.8, DeliveryDays: 2, Stock: 750, MinOrderQty: 60, Location: "Bengaluru", PaymentTerms: "Advance 20%", ReliabilityScore: 96, Category: "raw_materials"},
		{Name: "ZincRoute Distributors", Price: 64.90, Trust: 3.8, DeliveryDays: 9, Stock: 3600, MinOrderQty: 550, Location: "Bhubaneswar", PaymentTerms: "Net 60", ReliabilityScore: 78, Category: "raw_materials"},

		// Office Supplies (new category)
		{Name: "PaperVault Wholesale", Price: 32.50, Trust: 4.3, DeliveryDays: 3, Stock: 5000, MinOrderQty: 200, Location: "Mumbai", PaymentTerms: "Net 30", ReliabilityScore: 88, Category: "office_supplies"},
		{Name: "InkLine Traders", Price: 45.80, Trust: 4.6, DeliveryDays: 2, Stock: 3200, MinOrderQty: 100, Location: "Delhi", PaymentTerms: "Net 21", ReliabilityScore: 92, Category: "office_supplies"},
		{Name: "DeskEdge Suppliers", Price: 28.40, Trust: 3.9, DeliveryDays: 6, Stock: 6500, MinOrderQty: 300, Location: "Pune", PaymentTerms: "Net 45", ReliabilityScore: 82, Category: "office_supplies"},
		{Name: "OfficeFirst Distributors", Price: 38.70, Trust: 4.5, DeliveryDays: 3, Stock: 4100, MinOrderQty: 150, Location: "Bengaluru", PaymentTerms: "Net 20", ReliabilityScore: 91, Category: "office_supplies"},
		{Name: "NeatDesk Commerce", Price: 42.20, Trust: 4.7, DeliveryDays: 2, Stock: 2800, MinOrderQty: 80, Location: "Hyderabad", PaymentTerms: "Net 15", ReliabilityScore: 94, Category: "office_supplies"},
		{Name: "BulkOffice Wholesale", Price: 25.60, Trust: 3.7, DeliveryDays: 8, Stock: 8000, MinOrderQty: 500, Location: "Ahmedabad", PaymentTerms: "Net 60", ReliabilityScore: 79, Category: "office_supplies"},
		{Name: "ClipStream Traders", Price: 36.90, Trust: 4.4, DeliveryDays: 3, Stock: 4500, MinOrderQty: 120, Location: "Chennai", PaymentTerms: "Net 20", ReliabilityScore: 90, Category: "office_supplies"},
		{Name: "StoreSmart Suppliers", Price: 48.10, Trust: 4.8, DeliveryDays: 2, Stock: 2400, MinOrderQty: 60, Location: "Mumbai", PaymentTerms: "Net 10", ReliabilityScore: 96, Category: "office_supplies"},
		{Name: "ProDesk Distributors", Price: 31.30, Trust: 4.1, DeliveryDays: 5, Stock: 5500, MinOrderQty: 250, Location: "Noida", PaymentTerms: "Net 30", ReliabilityScore: 85, Category: "office_supplies"},
		{Name: "OfficePath Commerce", Price: 40.50, Trust: 4.5, DeliveryDays: 3, Stock: 3700, MinOrderQty: 100, Location: "Kolkata", PaymentTerms: "Net 21", ReliabilityScore: 91, Category: "office_supplies"},
		{Name: "MegaStash Traders", Price: 27.80, Trust: 3.8, DeliveryDays: 7, Stock: 7200, MinOrderQty: 400, Location: "Surat", PaymentTerms: "Net 45", ReliabilityScore: 80, Category: "office_supplies"},
		{Name: "QuickStat Wholesale", Price: 44.60, Trust: 4.6, DeliveryDays: 2, Stock: 2900, MinOrderQty: 90, Location: "Delhi", PaymentTerms: "Net 15", ReliabilityScore: 93, Category: "office_supplies"},
		{Name: "FlexOffice Suppliers", Price: 33.20, Trust: 4.2, DeliveryDays: 5, Stock: 4800, MinOrderQty: 180, Location: "Bengaluru", PaymentTerms: "Net 30", ReliabilityScore: 87, Category: "office_supplies"},
		{Name: "CrispLine Distributors", Price: 39.90, Trust: 4.4, DeliveryDays: 4, Stock: 3900, MinOrderQty: 130, Location: "Pune", PaymentTerms: "Net 20", ReliabilityScore: 89, Category: "office_supplies"},
		{Name: "VaultStock Commerce", Price: 50.00, Trust: 4.9, DeliveryDays: 1, Stock: 2000, MinOrderQty: 50, Location: "Mumbai", PaymentTerms: "Advance 20%", ReliabilityScore: 98, Category: "office_supplies"},

		// Packaging (new category)
		{Name: "WrapPro Wholesale", Price: 18.40, Trust: 4.3, DeliveryDays: 4, Stock: 10000, MinOrderQty: 500, Location: "Ahmedabad", PaymentTerms: "Net 30", ReliabilityScore: 88, Category: "packaging"},
		{Name: "BoxBridge Traders", Price: 22.70, Trust: 4.6, DeliveryDays: 3, Stock: 7500, MinOrderQty: 300, Location: "Mumbai", PaymentTerms: "Net 21", ReliabilityScore: 93, Category: "packaging"},
		{Name: "SecureWrap Suppliers", Price: 15.60, Trust: 3.8, DeliveryDays: 7, Stock: 14000, MinOrderQty: 1000, Location: "Surat", PaymentTerms: "Net 45", ReliabilityScore: 80, Category: "packaging"},
		{Name: "PackFirst Distributors", Price: 20.30, Trust: 4.5, DeliveryDays: 3, Stock: 8500, MinOrderQty: 400, Location: "Delhi", PaymentTerms: "Net 20", ReliabilityScore: 91, Category: "packaging"},
		{Name: "SealTight Commerce", Price: 24.80, Trust: 4.7, DeliveryDays: 2, Stock: 6000, MinOrderQty: 200, Location: "Bengaluru", PaymentTerms: "Net 15", ReliabilityScore: 95, Category: "packaging"},
		{Name: "BulkBox Wholesale", Price: 14.50, Trust: 3.7, DeliveryDays: 9, Stock: 18000, MinOrderQty: 1500, Location: "Kanpur", PaymentTerms: "Net 60", ReliabilityScore: 77, Category: "packaging"},
		{Name: "ClearPack Traders", Price: 19.90, Trust: 4.4, DeliveryDays: 4, Stock: 9200, MinOrderQty: 450, Location: "Hyderabad", PaymentTerms: "Net 30", ReliabilityScore: 90, Category: "packaging"},
		{Name: "PolyShield Suppliers", Price: 23.40, Trust: 4.8, DeliveryDays: 2, Stock: 5500, MinOrderQty: 200, Location: "Chennai", PaymentTerms: "Net 10", ReliabilityScore: 96, Category: "packaging"},
		{Name: "RapidBox Distributors", Price: 17.20, Trust: 4.0, DeliveryDays: 6, Stock: 11000, MinOrderQty: 700, Location: "Pune", PaymentTerms: "Net 30", ReliabilityScore: 84, Category: "packaging"},
		{Name: "SmartSeal Commerce", Price: 21.60, Trust: 4.5, DeliveryDays: 3, Stock: 7800, MinOrderQty: 350, Location: "Noida", PaymentTerms: "Net 21", ReliabilityScore: 91, Category: "packaging"},
		{Name: "CoreWrap Traders", Price: 16.80, Trust: 3.9, DeliveryDays: 8, Stock: 13000, MinOrderQty: 900, Location: "Ahmedabad", PaymentTerms: "Net 45", ReliabilityScore: 82, Category: "packaging"},
		{Name: "PackNest Wholesale", Price: 25.90, Trust: 4.9, DeliveryDays: 1, Stock: 4800, MinOrderQty: 150, Location: "Mumbai", PaymentTerms: "Advance 25%", ReliabilityScore: 97, Category: "packaging"},
		{Name: "LinkBox Suppliers", Price: 20.80, Trust: 4.3, DeliveryDays: 5, Stock: 8800, MinOrderQty: 420, Location: "Delhi", PaymentTerms: "Net 30", ReliabilityScore: 88, Category: "packaging"},
		{Name: "TuffPack Distributors", Price: 22.10, Trust: 4.6, DeliveryDays: 3, Stock: 7100, MinOrderQty: 310, Location: "Bengaluru", PaymentTerms: "Net 20", ReliabilityScore: 93, Category: "packaging"},
		{Name: "SwiftWrap Commerce", Price: 18.90, Trust: 4.2, DeliveryDays: 5, Stock: 9600, MinOrderQty: 480, Location: "Kolkata", PaymentTerms: "Net 30", ReliabilityScore: 87, Category: "packaging"},

		// Safety Equipment (new category)
		{Name: "SafeGuard Wholesale", Price: 55.30, Trust: 4.6, DeliveryDays: 3, Stock: 1800, MinOrderQty: 50, Location: "Mumbai", PaymentTerms: "Net 20", ReliabilityScore: 93, Category: "safety_equipment"},
		{Name: "ShieldLine Traders", Price: 61.80, Trust: 4.8, DeliveryDays: 2, Stock: 1200, MinOrderQty: 30, Location: "Delhi", PaymentTerms: "Net 15", ReliabilityScore: 96, Category: "safety_equipment"},
		{Name: "ProtectFirst Suppliers", Price: 48.40, Trust: 4.0, DeliveryDays: 6, Stock: 2600, MinOrderQty: 100, Location: "Pune", PaymentTerms: "Net 30", ReliabilityScore: 85, Category: "safety_equipment"},
		{Name: "ArmorLink Distributors", Price: 59.20, Trust: 4.7, DeliveryDays: 3, Stock: 1400, MinOrderQty: 40, Location: "Bengaluru", PaymentTerms: "Net 21", ReliabilityScore: 95, Category: "safety_equipment"},
		{Name: "SafeCore Commerce", Price: 52.70, Trust: 4.4, DeliveryDays: 4, Stock: 2000, MinOrderQty: 60, Location: "Hyderabad", PaymentTerms: "Net 20", ReliabilityScore: 91, Category: "safety_equipment"},
		{Name: "GuardMax Wholesale", Price: 44.90, Trust: 3.8, DeliveryDays: 8, Stock: 3200, MinOrderQty: 150, Location: "Surat", PaymentTerms: "Net 45", ReliabilityScore: 81, Category: "safety_equipment"},
		{Name: "HelmetHub Traders", Price: 63.50, Trust: 4.9, DeliveryDays: 2, Stock: 1000, MinOrderQty: 25, Location: "Chennai", PaymentTerms: "Net 10", ReliabilityScore: 97, Category: "safety_equipment"},
		{Name: "VisionPro Suppliers", Price: 57.40, Trust: 4.5, DeliveryDays: 3, Stock: 1600, MinOrderQty: 45, Location: "Kolkata", PaymentTerms: "Net 21", ReliabilityScore: 92, Category: "safety_equipment"},
		{Name: "TacShield Distributors", Price: 50.60, Trust: 4.2, DeliveryDays: 5, Stock: 2200, MinOrderQty: 75, Location: "Noida", PaymentTerms: "Net 30", ReliabilityScore: 87, Category: "safety_equipment"},
		{Name: "SafeSeal Commerce", Price: 65.00, Trust: 4.8, DeliveryDays: 2, Stock: 1100, MinOrderQty: 30, Location: "Mumbai", PaymentTerms: "Advance 20%", ReliabilityScore: 96, Category: "safety_equipment"},
		{Name: "ClearShield Wholesale", Price: 46.80, Trust: 3.9, DeliveryDays: 7, Stock: 2900, MinOrderQty: 120, Location: "Ahmedabad", PaymentTerms: "Net 45", ReliabilityScore: 83, Category: "safety_equipment"},
		{Name: "NormGear Traders", Price: 58.90, Trust: 4.6, DeliveryDays: 3, Stock: 1500, MinOrderQty: 40, Location: "Delhi", PaymentTerms: "Net 20", ReliabilityScore: 93, Category: "safety_equipment"},
		{Name: "IronGuard Suppliers", Price: 53.50, Trust: 4.3, DeliveryDays: 4, Stock: 1900, MinOrderQty: 55, Location: "Bengaluru", PaymentTerms: "Net 30", ReliabilityScore: 89, Category: "safety_equipment"},
		{Name: "SafeZone Distributors", Price: 60.40, Trust: 4.7, DeliveryDays: 3, Stock: 1300, MinOrderQty: 35, Location: "Hyderabad", PaymentTerms: "Net 15", ReliabilityScore: 94, Category: "safety_equipment"},
		{Name: "ProGuard Commerce", Price: 49.70, Trust: 4.1, DeliveryDays: 5, Stock: 2400, MinOrderQty: 80, Location: "Pune", PaymentTerms: "Net 30", ReliabilityScore: 86, Category: "safety_equipment"},

		// Chemicals (new category)
		{Name: "ChemSource India", Price: 38.60, Trust: 4.4, DeliveryDays: 4, Stock: 4200, MinOrderQty: 200, Location: "Mumbai", PaymentTerms: "Net 30", ReliabilityScore: 90, Category: "chemicals"},
		{Name: "ReagenRoute Traders", Price: 45.20, Trust: 4.7, DeliveryDays: 3, Stock: 2800, MinOrderQty: 100, Location: "Hyderabad", PaymentTerms: "Net 21", ReliabilityScore: 94, Category: "chemicals"},
		{Name: "SolventLink Wholesale", Price: 32.80, Trust: 3.9, DeliveryDays: 7, Stock: 5500, MinOrderQty: 350, Location: "Pune", PaymentTerms: "Net 45", ReliabilityScore: 83, Category: "chemicals"},
		{Name: "CatalystBridge Suppliers", Price: 51.40, Trust: 4.8, DeliveryDays: 2, Stock: 2000, MinOrderQty: 80, Location: "Bengaluru", PaymentTerms: "Advance 20%", ReliabilityScore: 96, Category: "chemicals"},
		{Name: "MixPath Distributors", Price: 41.90, Trust: 4.5, DeliveryDays: 4, Stock: 3300, MinOrderQty: 150, Location: "Ahmedabad", PaymentTerms: "Net 20", ReliabilityScore: 91, Category: "chemicals"},
		{Name: "PureReagen Commerce", Price: 55.70, Trust: 4.9, DeliveryDays: 2, Stock: 1800, MinOrderQty: 60, Location: "Delhi", PaymentTerms: "Net 10", ReliabilityScore: 97, Category: "chemicals"},
		{Name: "IndusChem Traders", Price: 29.30, Trust: 3.7, DeliveryDays: 9, Stock: 7000, MinOrderQty: 500, Location: "Surat", PaymentTerms: "Net 60", ReliabilityScore: 78, Category: "chemicals"},
		{Name: "BaseOil Wholesale", Price: 36.50, Trust: 4.2, DeliveryDays: 5, Stock: 4600, MinOrderQty: 250, Location: "Chennai", PaymentTerms: "Net 30", ReliabilityScore: 87, Category: "chemicals"},
		{Name: "FluidCore Suppliers", Price: 48.80, Trust: 4.6, DeliveryDays: 3, Stock: 2500, MinOrderQty: 120, Location: "Kolkata", PaymentTerms: "Net 21", ReliabilityScore: 93, Category: "chemicals"},
		{Name: "AcidBridge Distributors", Price: 43.60, Trust: 4.4, DeliveryDays: 4, Stock: 3100, MinOrderQty: 140, Location: "Noida", PaymentTerms: "Net 20", ReliabilityScore: 90, Category: "chemicals"},
		{Name: "SynthLine Commerce", Price: 53.20, Trust: 4.7, DeliveryDays: 3, Stock: 2200, MinOrderQty: 90, Location: "Hyderabad", PaymentTerms: "Net 15", ReliabilityScore: 95, Category: "chemicals"},
		{Name: "ChemiTrack Wholesale", Price: 31.70, Trust: 3.8, DeliveryDays: 8, Stock: 6200, MinOrderQty: 420, Location: "Bhopal", PaymentTerms: "Net 45", ReliabilityScore: 81, Category: "chemicals"},
		{Name: "ProtonPath Traders", Price: 40.20, Trust: 4.3, DeliveryDays: 5, Stock: 3800, MinOrderQty: 180, Location: "Mumbai", PaymentTerms: "Net 30", ReliabilityScore: 88, Category: "chemicals"},
		{Name: "ClearBase Suppliers", Price: 57.30, Trust: 4.9, DeliveryDays: 1, Stock: 1500, MinOrderQty: 50, Location: "Bengaluru", PaymentTerms: "Advance 25%", ReliabilityScore: 98, Category: "chemicals"},
		{Name: "LabLine Distributors", Price: 46.90, Trust: 4.5, DeliveryDays: 3, Stock: 2700, MinOrderQty: 110, Location: "Pune", PaymentTerms: "Net 20", ReliabilityScore: 92, Category: "chemicals"},

		// Textiles (new category)
		{Name: "FabricRoute Wholesale", Price: 26.40, Trust: 4.3, DeliveryDays: 5, Stock: 8000, MinOrderQty: 500, Location: "Surat", PaymentTerms: "Net 30", ReliabilityScore: 88, Category: "textiles"},
		{Name: "ThreadBridge Traders", Price: 31.80, Trust: 4.6, DeliveryDays: 3, Stock: 5500, MinOrderQty: 300, Location: "Ahmedabad", PaymentTerms: "Net 21", ReliabilityScore: 93, Category: "textiles"},
		{Name: "WeavePath Suppliers", Price: 22.60, Trust: 3.9, DeliveryDays: 7, Stock: 11000, MinOrderQty: 800, Location: "Tiruppur", PaymentTerms: "Net 45", ReliabilityScore: 82, Category: "textiles"},
		{Name: "YarnLink Distributors", Price: 28.90, Trust: 4.5, DeliveryDays: 4, Stock: 7200, MinOrderQty: 400, Location: "Mumbai", PaymentTerms: "Net 20", ReliabilityScore: 91, Category: "textiles"},
		{Name: "TextileHub Commerce", Price: 35.40, Trust: 4.7, DeliveryDays: 2, Stock: 4600, MinOrderQty: 200, Location: "Delhi", PaymentTerms: "Net 15", ReliabilityScore: 95, Category: "textiles"},
		{Name: "BulkWeave Wholesale", Price: 19.80, Trust: 3.7, DeliveryDays: 9, Stock: 14000, MinOrderQty: 1200, Location: "Ludhiana", PaymentTerms: "Net 60", ReliabilityScore: 78, Category: "textiles"},
		{Name: "SilkRoad Traders", Price: 42.10, Trust: 4.8, DeliveryDays: 3, Stock: 3800, MinOrderQty: 150, Location: "Bengaluru", PaymentTerms: "Advance 20%", ReliabilityScore: 96, Category: "textiles"},
		{Name: "CottonLink Suppliers", Price: 24.50, Trust: 4.1, DeliveryDays: 6, Stock: 9500, MinOrderQty: 650, Location: "Coimbatore", PaymentTerms: "Net 30", ReliabilityScore: 85, Category: "textiles"},
		{Name: "FiberCore Distributors", Price: 29.70, Trust: 4.4, DeliveryDays: 4, Stock: 6800, MinOrderQty: 380, Location: "Surat", PaymentTerms: "Net 20", ReliabilityScore: 90, Category: "textiles"},
		{Name: "DrapeLine Commerce", Price: 37.60, Trust: 4.6, DeliveryDays: 3, Stock: 4200, MinOrderQty: 220, Location: "Hyderabad", PaymentTerms: "Net 21", ReliabilityScore: 93, Category: "textiles"},
		{Name: "LoominBulk Wholesale", Price: 21.30, Trust: 3.8, DeliveryDays: 8, Stock: 12500, MinOrderQty: 950, Location: "Panipat", PaymentTerms: "Net 45", ReliabilityScore: 80, Category: "textiles"},
		{Name: "CraftFiber Traders", Price: 33.90, Trust: 4.5, DeliveryDays: 4, Stock: 5900, MinOrderQty: 320, Location: "Ahmedabad", PaymentTerms: "Net 30", ReliabilityScore: 91, Category: "textiles"},
		{Name: "PolyWeft Suppliers", Price: 27.20, Trust: 4.2, DeliveryDays: 6, Stock: 8800, MinOrderQty: 580, Location: "Tiruppur", PaymentTerms: "Net 30", ReliabilityScore: 87, Category: "textiles"},
		{Name: "PureLoom Distributors", Price: 39.50, Trust: 4.7, DeliveryDays: 3, Stock: 4000, MinOrderQty: 180, Location: "Mumbai", PaymentTerms: "Net 15", ReliabilityScore: 95, Category: "textiles"},
		{Name: "WarpCore Commerce", Price: 23.80, Trust: 4.0, DeliveryDays: 7, Stock: 10200, MinOrderQty: 750, Location: "Ludhiana", PaymentTerms: "Net 45", ReliabilityScore: 84, Category: "textiles"},
	}

	return database.Clauses(clause.OnConflict{
		Columns:   []clause.Column{{Name: "name"}},
		DoNothing: true,
	}).Create(&vendors).Error
}